# Generated by Django 5.2.7 on 2025-11-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
