# Generated by Django 5.2.7 on 2025-10-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
